spring:
  datasource:
    url: jdbc:mysql://10.11.0.156:3306/bpms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&allowMultiQueries=true
    username: bpms
    password: bpms@123
  profiles:
    active: dubbo

mybatis:
  mapper-locations: Account.map.xml
multi-tenant:
  tenantIdColumn: id
logging:
  level:
    cn.sexycode.tenancy.demo:
      debug
server:
  port: 8088

---
spring:
  profiles: dubbo
  dubbo:
    application:
      name: demo
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20881
    scan: cn.sexycode.tenancy.demo.dubbo